### ISSUE TITLE
paper processor crashes on mysql insert with "incorrect string value"

### ISSUE THREAD

**Issue by wo** [wo/opp-tools#94]
```
[] authors: 'Teddy Seidenfeld'
[] title: 'Three degrees of Imprecise Probability [IP] Theory'
[] confidence: 1

[] extracting abstract
[] reducing confidence by 0.92760363709129 because abstract score
[] abstract: 'Here, I rely freely on enjoyable collaborations/discussions with: Mark Schervish, Jay Kadane, Fabio Cozman, Erik Quaeghebeur, and Matthias Troffaes; Each of them has the good sense and keen judgment to disagree on some particulars in what follows!'
[] confidence: 0.92760363709129
[] reducing confidence by 0.920595049471438 because parsing quality
[] reducing confidence by 1.04512516364937 because alternative parsings
[] reducing confidence by 1 because TITLE chunk probability 0.856058574631599
[] reducing confidence by 1 because AUTHOR chunk probability 0.806444824961982
[] adjusted confidence: 0.892481828568413

Traceback (most recent call last):
  File "bin/scraperdaemon.py", line 70, in <module>
    daemon.start()
  File "bin/scraperdaemon.py", line 38, in start
    self.run()
  File "bin/scraperdaemon.py", line 49, in run
    scraper.scrape(source)
  File "/home/wo/opp-tools/bin/../opp/scraper.py", line 139, in scrape
    process_link(li)
  File "/home/wo/opp-tools/bin/../opp/scraper.py", line 316, in process_link
    doc.update_db()
  File "/home/wo/opp-tools/bin/../opp/models.py", line 500, in update_db
    cur.execute(query, values)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9D\\x91\\xB0\\xF0\\x9D...' for column 'content' at row 1")
Exception ignored in: <bound method ActualBrowser.__del__ of <opp.browser.ActualBrowser (session="e62b5872-ec46-4d66-9ecf-57fcbcd1ccc1")>>
Traceback (most recent call last):
  File "/home/wo/opp-tools/bin/../opp/browser.py", line 32, in __del__
  File "/usr/lib/python3.4/logging/__init__.py", line 1262, in debug
  File "/usr/lib/python3.4/logging/__init__.py", line 1409, in _log
  File "/usr/lib/python3.4/logging/__init__.py", line 1419, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1481, in callHandlers
  File "/usr/lib/python3.4/logging/__init__.py", line 853, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1040, in emit
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
```

**Comment by wo** [comment]
Turns out Seidenfeld uses a 4-byte unicode string which my mysql table's utf8 doesn't support. The proper response would be to convert the whole db to utf8mb4, but that looks laborious.

**Comment by wo** [comment]
Fixed the mysql db now. (036a570)
